from enum import StrEnum

from pydantic import BaseModel, Field, field_validator


class ChatMessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class ChatMessage(BaseModel):
    role: ChatMessageRole = Field(
        description="Message role used by chat completion models.",
    )
    content: str = Field(
        min_length=1,
        max_length=4000,
        description="Message text content.",
    )

    def to_openai_dict(self) -> dict[str, str]:
        return {
            "role": self.role.value,
            "content": self.content,
        }


class ChatRequest(BaseModel):
    message: str = Field(
        min_length=1,
        max_length=4000,
        description="User message sent to the AI service.",
    )
    history: list[ChatMessage] = Field(
        default_factory=list,
        max_length=20,
        description="Previous user and assistant messages in this conversation.",
    )

    @field_validator("history")
    @classmethod
    def reject_system_messages_in_history(
        cls,
        history: list[ChatMessage],
    ) -> list[ChatMessage]:
        for message in history:
            if message.role == ChatMessageRole.SYSTEM:
                raise ValueError("history must not contain system messages")
        return history


class ChatResponse(BaseModel):
    reply: str = Field(
        min_length=1,
        description="Reply returned by the AI service.",
    )


class ConsoleChatRequest(ChatRequest):
    conversation_id: str | None = Field(
        default=None,
        min_length=1,
        max_length=128,
        description="Frontend conversation id used to keep one chat thread together.",
    )


class ConsoleChatResponse(BaseModel):
    reply: str = Field(
        min_length=1,
        description="Reply returned to the frontend console.",
    )
    conversation_id: str = Field(
        min_length=1,
        max_length=128,
        description="Conversation id echoed or generated by the AI service.",
    )
    trace_id: str = Field(
        min_length=1,
        description="Trace id for frontend and backend troubleshooting.",
    )
    mode: str = Field(
        default="tool_chat",
        description="Backend AI route used for this response.",
    )
